stages:
- build

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - apk add --no-cache coreutils
  script:
  - CI_JOB_TIMESTAMP=$(date --utc +%Y-%m-%d)
  - CI_COMMIT_SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c 1-8)
  - TAG_DATE_SHA=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:build-$CI_JOB_TIMESTAMP-commit-$CI_COMMIT_SHORT_SHA
  - docker build -t $TAG_DATE_SHA .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $TAG_DATE_SHA

  only:
  - develop

